In [1]:
pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [2]:
from google.colab import userdata
import os

os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')

In [3]:
!kaggle datasets download -d milanvaddoriya/data-science-job-salary

Downloading data-science-job-salary.zip to /content
  0% 0.00/9.97k [00:00<?, ?B/s]
100% 9.97k/9.97k [00:00<00:00, 12.3MB/s]

In [4]:
!unzip data-science-job-salary.zip

Archive:  data-science-job-salary.zip
  inflating: datascience_salaries.csv

In [5]:
import pandas as pd
df = pd.read_csv('datascience_salaries.csv')

In [6]:
df

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000
...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,228000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,115000
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,76000
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,68000
1170,2259,ML Ops,Internship,Senior,New York City,USD,135000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1171 non-null   int64
 1   job_title         1171 non-null   object
 2   job_type          1171 non-null   object
 3   experience_level  1171 non-null   object
 4   location          1171 non-null   object
 5   salary_currency   1171 non-null   object
 6   salary            1171 non-null   int64
dtypes: int64(2), object(5)
memory usage: 64.2+ KB

In [ ]:
df.isnull().sum() # No missing values!

Unnamed: 0          0
job_title           0
job_type            0
experience_level    0
location            0
salary_currency     0
salary              0
dtype: int64

In [ ]:
df.duplicated().sum() # No duplicates values!

0

In [7]:
min_salary = df['salary'].min()
max_salary = df['salary'].max()

# Apply Min-Max normalization to the 'salary' column
df['normalized_salary'] = (df['salary'] - min_salary) / (max_salary - min_salary)

In [16]:
df

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary,normalized_salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010
1,2,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545
2,3,Data scientist,Full Time,Senior,London,USD,68000,0.191919
3,4,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545
4,5,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010
...,...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,228000,1.000000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,115000,0.429293
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,76000,0.232323
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,68000,0.191919
1170,2259,ML Ops,Internship,Senior,New York City,USD,135000,0.530303

In [22]:
final_df = df.drop(columns='Unnamed: 0')

In [23]:
final_df

,job_title,job_type,experience_level,location,salary_currency,salary,normalized_salary
0,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010
1,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545
2,Data scientist,Full Time,Senior,London,USD,68000,0.191919
3,Data scientist,Full Time,Senior,Boston,USD,120000,0.454545
4,Data scientist,Full Time,Senior,New York City,USD,149000,0.601010
...,...,...,...,...,...,...,...
1166,ML Ops,Full Time,Senior,Toronto,USD,228000,1.000000
1167,ML Ops,Full Time,Senior,Boston,USD,115000,0.429293
1168,ML Ops,Full Time,Senior,Delhi,USD,76000,0.232323
1169,ML Ops,Full Time,Senior,San Francisco,USD,68000,0.191919
1170,ML Ops,Internship,Senior,New York City,USD,135000,0.530303

In [24]:
final_df['experience_level'] = pd.Categorical(final_df['experience_level'], categories=['Entry', 'Mid', 'Senior', 'Executive'], ordered=True)

In [25]:
final_df.groupby('experience_level').describe()

                 salary                                                \
                  count          mean           std      min      25%
experience_level
Entry             126.0  36111.111111  16151.394849  30000.0  30000.0
Mid               305.0  51786.885246  20609.874641  30000.0  40000.0
Senior            727.0  75088.033012  33560.733276  30000.0  63000.0
Executive          13.0  76076.923077  46860.540505  41000.0  43000.0

                                              normalized_salary            \
                      50%       75%       max             count      mean
experience_level
Entry             30000.0   36000.0  140000.0             126.0  0.030864
Mid               51000.0   51000.0  160000.0             305.0  0.110035
Senior            68000.0   69000.0  228000.0             727.0  0.227717
Executive         46000.0  110000.0  175000.0              13.0  0.232712


                       std       min       25%       50%       75%       max
experience_level
Entry             0.081573  0.000000  0.000000  0.000000  0.030303  0.555556
Mid               0.104090  0.000000  0.050505  0.106061  0.106061  0.656566
Senior            0.169499  0.000000  0.166667  0.191919  0.196970  1.000000
Executive         0.236669  0.055556  0.065657  0.080808  0.404040  0.732323

In [26]:
grouped_data = final_df.groupby('experience_level')['salary'].agg(['mean', 'median'])

In [27]:
grouped_data

                          mean   median
experience_level
Entry             36111.111111  30000.0
Mid               51786.885246  51000.0
Senior            75088.033012  68000.0
Executive         76076.923077  46000.0