In [161]:
import pandas as pd
mental_health_data = pd.read_csv('survey.csv')
mental_health_data

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [162]:
cleaned_mental_health_data = mental_health_data

In [163]:
cleaned_mental_health_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [164]:
# Drop column 'comments' because its 87% missing values so its not relevant for us
cleaned_mental_health_data = cleaned_mental_health_data.drop(columns=['comments'])

In [165]:
# Drop column 'comments' because  its not relevant for us
cleaned_mental_health_data = cleaned_mental_health_data.drop(columns=['state'])

In [166]:
cleaned_mental_health_data

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,NaN,No,Yes,Often,6-25,No,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,M,United States,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,NaN,No,No,Rarely,6-25,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,NaN,No,No,Never,100-500,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,No,No,Yes,NaN,26-100,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26 01:07:35,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07 12:36:58,34,male,United States,No,Yes,Yes,Sometimes,More than 1000,No,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30 21:25:06,46,f,United States,No,No,No,NaN,100-500,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01 23:04:31,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [167]:
cleaned_mental_health_data['Gender'].replace(['man', 'Male ', 'm', 'maile', 'Male (CIS)','Cis Man' ,'Cis Male', 'msle', 'Mail', 'Make', 'Mal', 'Malr', 'Male-ish', 'Man', 'M', "male"], 'Male', inplace=True)
cleaned_mental_health_data['Gender'].replace([ 'Female ', 'Female (cis)','cis-female/femme', 'feMale', 'F', 'f', 'woman', 'Woman', 'Cis Female', 'Cis FeMale', 'femail', 'Femake', 'female'], 'Female', inplace=True)
cleaned_mental_health_data.loc[~cleaned_mental_health_data['Gender'].isin(['Male', 'Female']), 'Gender'] = 'Other'

/var/folders/0y/9ghc01ls5k5bh2rpf5gh4whc0000gn/T/ipykernel_62552/2349749651.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_mental_health_data['Gender'].replace(['man', 'Male ', 'm', 'maile', 'Male (CIS)','Cis Man' ,'Cis Male', 'msle', 'Mail', 'Make', 'Mal', 'Malr', 'Male-ish', 'Man', 'M', "male"], 'Male', inplace=True)

In [168]:
cleaned_mental_health_data

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,NaN,No,Yes,Often,6-25,No,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,Male,United States,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,NaN,No,No,Rarely,6-25,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,NaN,No,No,Never,100-500,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,Male,United Kingdom,No,No,Yes,NaN,26-100,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26 01:07:35,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07 12:36:58,34,Male,United States,No,Yes,Yes,Sometimes,More than 1000,No,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30 21:25:06,46,Female,United States,No,No,No,NaN,100-500,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01 23:04:31,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [169]:
Q1A = cleaned_mental_health_data['Age'].quantile(0.25)
Q3A = cleaned_mental_health_data['Age'].quantile(0.75)
IQRA = Q3A - Q1A
lower_boundA = Q1A - 1.5 * IQRA
upper_boundA = Q3A + 1.5 * IQRA
print(lower_boundA,upper_boundA)
outliers_data_ages = cleaned_mental_health_data[(cleaned_mental_health_data['Age'] < lower_boundA) | (cleaned_mental_health_data['Age'] > upper_boundA)]
new_cleaned_mental_data = cleaned_mental_health_data[(cleaned_mental_health_data['Age'] >= lower_boundA) & (cleaned_mental_health_data['Age'] <= upper_boundA)]

13.5 49.5

In [170]:
outliers_data_ages

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
38,2014-08-27 11:42:08,50,Male,United States,No,No,No,NaN,100-500,No,...,Don't know,Don't know,No,No,Some of them,Yes,No,Maybe,Don't know,No
143,2014-08-27 12:39:14,-29,Male,United States,No,No,No,NaN,More than 1000,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,No,No,Don't know,No
294,2014-08-27 14:15:57,56,Male,United States,No,No,Yes,Never,More than 1000,No,...,Don't know,Don't know,No,Maybe,Yes,Some of them,No,Maybe,Don't know,No
297,2014-08-27 14:18:41,60,Male,United States,No,No,No,NaN,More than 1000,No,...,Don't know,Don't know,No,No,Some of them,Yes,Maybe,Maybe,Yes,No
347,2014-08-27 14:45:45,54,Male,United States,No,Yes,Yes,Never,More than 1000,No,...,Don't know,Don't know,No,No,No,Yes,No,No,Don't know,No
364,2014-08-27 15:05:21,329,Male,United States,No,No,Yes,Often,6-25,Yes,...,Don't know,Don't know,Maybe,No,Some of them,No,No,No,No,No
372,2014-08-27 15:21:59,55,Male,United States,No,Yes,Yes,Rarely,More than 1000,No,...,Yes,Very easy,No,No,Yes,Yes,No,No,Yes,No
390,2014-08-27 15:24:47,99999999999,Other,Zimbabwe,Yes,Yes,Yes,Often,1-5,No,...,No,Very difficult,Yes,Yes,No,No,Yes,No,No,Yes
419,2014-08-27 15:31:40,55,Male,United States,No,Yes,Yes,Sometimes,1-5,Yes,...,Don't know,Don't know,Yes,Maybe,No,No,No,No,No,Yes
466,2014-08-27 16:06:46,57,Male,United States,No,Yes,Yes,Rarely,More than 1000,No,...,Don't know,Don't know,Maybe,No,Some of them,Yes,No,Maybe,No,No
471,2014-08-27 16:13:40,58,Male,United States,No,No,Yes,Rarely,More than 1000,No,...,Yes,Somewhat easy,Maybe,No,Some of them,Yes,No,Yes,Yes,No
475,2014-08-27 16:15:26,57,Male,United States,No,No,Yes,Sometimes,More than 1000,No,...,Don't know,Don't know,Maybe,Maybe,No,No,No,Maybe,Don't know,No
498,2014-08-27 16:28:20,54,Male,United Kingdom,No,No,Yes,Sometimes,More than 1000,Yes,...,Yes,Very easy,No,No,Yes,Yes,Maybe,Maybe,No,No
520,2014-08-27 17:12:01,62,Male,United States,No,No,No,Never,More than 1000,No,...,Don't know,Don't know,Maybe,No,Some of them,Yes,Maybe,Maybe,Yes,No
527,2014-08-27 17:33:52,51,Male,New Zealand,No,No,Yes,Sometimes,26-100,Yes,...,No,Somewhat difficult,Yes,Yes,No,No,No,No,Don't know,Yes
560,2014-08-27 19:17:07,65,Male,United States,Yes,No,No,NaN,6-25,Yes,...,Don't know,Very easy,Maybe,No,Some of them,No,No,No,Yes,No
574,2014-08-27 20:52:20,50,Male,United States,No,No,No,Never,26-100,Yes,...,Don't know,Don't know,No,No,No,No,No,Maybe,No,No
581,2014-08-27 21:21:31,50,Male,United States,No,Yes,No,NaN,100-500,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Maybe,Maybe,Don't know,No
606,2014-08-27 23:10:16,50,Male,United States,No,No,No,Sometimes,1-5,Yes,...,Don't know,Don't know,Yes,Maybe,Some of them,Some of them,No,Maybe,Don't know,No
631,2014-08-28 02:41:47,56,Male,United States,No,Yes,Yes,Rarely,6-25,No,...,Don't know,Don't know,Yes,Maybe,Some of them,Some of them,No,No,Don't know,No
643,2014-08-28 03:36:10,57,Male,United States,No,No,No,Never,26-100,No,...,Yes,Somewhat difficult,Yes,Maybe,No,No,No,Maybe,Don't know,Yes
652,2014-08-28 04:11:27,54,Male,United Kingdom,Yes,Yes,Yes,Sometimes,1-5,Yes,...,Don't know,Very easy,No,No,Some of them,Yes,Yes,Yes,Don't know,Yes
715,2014-08-28 10:07:53,-1726,Male,United Kingdom,No,No,Yes,Sometimes,26-100,No,...,Don't know,Somewhat difficult,Yes,No,No,No,No,Maybe,Don't know,No
734,2014-08-28 10:35:55,5,Male,United States,No,No,No,NaN,100-500,No,...,Don't know,Somewhat easy,No,No,Yes,Yes,No,No,Yes,No
856,2014-08-28 17:01:25,51,Male,United States,No,No,No,Never,More than 1000,Yes,...,Yes,Very easy,No,No,Yes,Yes,No,No,Yes,No
870,2014-08-28 17:11:48,56,Male,United States,No,No,Yes,Rarely,More than 1000,Yes,...,Yes,Somewhat easy,No,No,Yes,Yes,Yes,Yes,Yes,No
895,2014-08-28 17:45:21,51,Male,United States,No,No,No,NaN,100-500,No,...,Don't know,Somewhat difficult,No,No,Some of them,Yes,No,No,Don't know,No
898,2014-08-28 17:47:49,50,Male,United States,Yes,No,No,Never,1-5,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
904,2014-08-28 17:59:54,51,Male,United States,Yes,No,No,Never,1-5,No,...,Yes,Somewhat difficult,No,No,Some of them,Some of them,Maybe,Maybe,Don't know,No
911,2014-08-28 18:21:23,53,Male,United States,No,No,Yes,Rarely,6-25,Yes,...,Don't know,Don't know,Maybe,Maybe,Some of them,No,No,No,Don't know,No
952,2014-08-29 01:20:32,61,Male,South Africa,Yes,No,Yes,Sometimes,1-5,Yes,...,Don't know,Very difficult,Yes,Maybe,Some of them,Yes,No,Maybe,No,Yes
964,2014-08-29 05:47:19,55,Male,United Kingdom,No,No,Yes,Often,More than 1000,No,...,Don't know,Somewhat easy,Yes,Maybe,No,Some of them,No,Maybe,No,Yes
989,2014-08-29 09:10:58,8,Other,"Bahamas, The",Yes,Yes,Yes,Often,1-5,Yes,...,Yes,Very easy,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
1090,2014-08-29 17:26:15,11,Male,United States,Yes,No,No,Never,1-5,Yes,...,Yes,Very easy,No,No,Some of them,Some of them,No,Maybe,Yes,No
1106,2014-08-30 03:55:19,50,Male,France,Yes,No,Yes,Sometimes,26-100,Yes,...,Don't know,Don't know,Maybe,Maybe,Some of them,Yes,No,No,Don't know,No
1127,2014-08-30 20:55:11,-1,Other,United States,Yes,Yes,Yes,Often,1-5,Yes,...,Yes,Very easy,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
1159,2014-09-03 01:32:51,51,Male,Singapore,No,No,No,Never,More than 1000,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1182,2014-10-02 21:25:16,72,Female,United States,No,Yes,Yes,Never,500-1000,Yes,...,Don't know,Somewhat easy,Maybe,Maybe,Some of them,Yes,No,No,Don't know,Yes
1186,2014-11-06 11:24:38,56,Female,United States,Yes,No,No,Rarely,1-5,Yes,...,Don't know,Don't know,Maybe,Maybe,No,No,No,No,Don't know,No
1236,2015-02-24 10:32:32,60,Male,United States,No,No,Yes,Often,More than 1000,Yes,...,Don't know,Somewhat easy,Maybe,Maybe,Some of them,No,No,Maybe,Don't know,No

In [171]:
new_cleaned_mental_data

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,NaN,No,Yes,Often,6-25,No,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,Male,United States,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,NaN,No,No,Rarely,6-25,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,NaN,No,No,Never,100-500,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,Male,United Kingdom,No,No,Yes,NaN,26-100,No,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26 01:07:35,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07 12:36:58,34,Male,United States,No,Yes,Yes,Sometimes,More than 1000,No,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30 21:25:06,46,Female,United States,No,No,No,NaN,100-500,Yes,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01 23:04:31,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [172]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
new_cleaned_mental_data.loc[:, 'Age_normalized'] = scaler.fit_transform(new_cleaned_mental_data[['Age']])

/var/folders/0y/9ghc01ls5k5bh2rpf5gh4whc0000gn/T/ipykernel_62552/1567201540.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_cleaned_mental_data.loc[:, 'Age_normalized'] = scaler.fit_transform(new_cleaned_mental_data[['Age']])

In [173]:
new_cleaned_mental_data

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,Age_normalized
0,2014-08-27 11:29:31,37,Female,United States,NaN,No,Yes,Often,6-25,No,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,0.612903
1,2014-08-27 11:29:37,44,Male,United States,NaN,No,No,Rarely,More than 1000,No,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,0.838710
2,2014-08-27 11:29:44,32,Male,Canada,NaN,No,No,Rarely,6-25,No,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,0.451613
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,0.419355
4,2014-08-27 11:30:22,31,Male,United States,NaN,No,No,Never,100-500,Yes,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,0.419355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,Male,United Kingdom,No,No,Yes,NaN,26-100,No,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,0.258065
1255,2015-09-26 01:07:35,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,0.451613
1256,2015-11-07 12:36:58,34,Male,United States,No,Yes,Yes,Sometimes,More than 1000,No,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,0.516129
1257,2015-11-30 21:25:06,46,Female,United States,No,No,No,NaN,100-500,Yes,...,Don't know,Yes,No,No,No,No,No,No,No,0.903226
1258,2016-02-01 23:04:31,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,0.225806

In [174]:
# Drop rows with missing data in columns: 'self_employed', 'work_interfere'
new_cleaned_mental_data = new_cleaned_mental_data.dropna(subset=['self_employed', 'work_interfere'])

In [175]:
new_cleaned_mental_data

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,Age_normalized
18,2014-08-27 11:34:53,46,Male,United States,Yes,Yes,No,Sometimes,1-5,Yes,...,Very easy,No,No,Yes,Yes,No,Yes,Yes,Yes,0.903226
20,2014-08-27 11:35:12,29,Male,United States,No,Yes,Yes,Sometimes,100-500,No,...,Somewhat difficult,Maybe,No,Some of them,Some of them,No,No,No,No,0.354839
21,2014-08-27 11:35:24,31,Male,United States,Yes,No,No,Never,1-5,Yes,...,Somewhat difficult,No,No,Some of them,Some of them,No,Maybe,Yes,No,0.419355
22,2014-08-27 11:35:48,46,Male,United States,No,No,Yes,Often,26-100,Yes,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,No,No,0.903226
23,2014-08-27 11:36:24,41,Male,United States,No,No,Yes,Never,More than 1000,No,...,Don't know,Maybe,No,No,No,No,Yes,Don't know,No,0.741935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1252,2015-08-20 16:52:09,29,Male,United States,No,Yes,Yes,Sometimes,100-500,Yes,...,Don't know,Yes,No,Some of them,No,No,Maybe,No,No,0.354839
1253,2015-08-25 19:59:38,36,Male,United States,No,Yes,No,Rarely,More than 1000,No,...,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No,0.580645
1255,2015-09-26 01:07:35,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,0.451613
1256,2015-11-07 12:36:58,34,Male,United States,No,Yes,Yes,Sometimes,More than 1000,No,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,0.516129
1258,2016-02-01 23:04:31,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,0.225806

In [176]:
test_data = new_cleaned_mental_data
# Define age groups
age_bins = [18, 25, 35, 45, 50]  # Define your age groups as needed
age_labels = ['18-24', '25-34', '35-44', '45-49']
test_data.loc[:,'Age_Group'] = pd.cut(test_data['Age'], bins=age_bins, labels=age_labels, right=False)

# Group the data by age group and calculate the proportion of respondents who sought treatment
age_group_distribution = test_data.groupby('Age_Group')['treatment'].value_counts(normalize=True).unstack() * 100

/var/folders/0y/9ghc01ls5k5bh2rpf5gh4whc0000gn/T/ipykernel_62552/3793288656.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data.loc[:,'Age_Group'] = pd.cut(test_data['Age'], bins=age_bins, labels=age_labels, right=False)
/var/folders/0y/9ghc01ls5k5bh2rpf5gh4whc0000gn/T/ipykernel_62552/3793288656.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_group_distribution = test_data.groupby('Age_Group')['treatment'].value_counts(normalize=True).unstack() * 100

In [182]:
age_group_distribution

treatment         No        Yes
Age_Group
18-24      40.517241  59.482759
25-34      37.222222  62.777778
35-44      33.593750  66.406250
45-49      28.125000  71.875000

In [201]:
gender_distribution = test_data.groupby('Gender')['treatment'].value_counts(normalize=True).unstack() * 100
gender_distribution

treatment         No        Yes
Gender
Female     20.098039  79.901961
Male       41.274238  58.725762
Other      22.222222  77.777778

In [200]:
country_distribution2 = test_data.groupby('Country')['treatment'].value_counts(normalize=True).unstack() * 100
country_distribution2

treatment                       No         Yes
Country
Australia                35.000000   65.000000
Austria                 100.000000         NaN
Belgium                  75.000000   25.000000
Bosnia and Herzegovina  100.000000         NaN
Brazil                   75.000000   25.000000
Bulgaria                       NaN  100.000000
Canada                   37.288136   62.711864
China                   100.000000         NaN
Colombia                100.000000         NaN
Croatia                        NaN  100.000000
Czech Republic          100.000000         NaN
Denmark                        NaN  100.000000
Finland                  50.000000   50.000000
France                   66.666667   33.333333
Georgia                 100.000000         NaN
Germany                  36.363636   63.636364
Hungary                 100.000000         NaN
India                    40.000000   60.000000
Ireland                  43.478261   56.521739
Israel                  100.000000         NaN
Italy                    83.333333   16.666667
Japan                          NaN  100.000000
Mexico                   50.000000   50.000000
Moldova                        NaN  100.000000
Netherlands              57.894737   42.105263
New Zealand              42.857143   57.142857
Philippines             100.000000         NaN
Poland                   42.857143   57.142857
Portugal                100.000000         NaN
Russia                  100.000000         NaN
Singapore                66.666667   33.333333
Slovenia                       NaN  100.000000
South Africa             25.000000   75.000000
Sweden                   60.000000   40.000000
Switzerland              40.000000   60.000000
Thailand                100.000000         NaN
United Kingdom           36.296296   63.703704
United States            32.286213   67.713787

In [209]:
respondent_counts = test_data.groupby('Country')['treatment'].count()

min = 10
filtered_countries = respondent_counts[respondent_counts>= min].index

filtered_menthal_health_rates = test_data[test_data['Country'].isin(filtered_countries)].groupby('Country')['treatment'].apply(lambda x: (x == "Yes").mean()).reset_index()
sorted_filtered_rates_desc = filtered_menthal_health_rates.sort_values('treatment', ascending= False)
sorted_filtered_rates_asc = filtered_menthal_health_rates.sort_values('treatment', ascending= True)

print("Countries with the highest reported rates of mental health issues (filtered):")
sorted_filtered_rates_desc.head()

Countries with the highest reported rates of mental health issues (filtered):

          Country  treatment
6   United States   0.677138
0       Australia   0.650000
5  United Kingdom   0.637037
2         Germany   0.636364
1          Canada   0.627119

In [207]:
print("\nCountries with the lowest reported rates of mental health issues (filtered):")
sorted_filtered_rates_asc.head()

Countries with the lowest reported rates of mental health issues (filtered):

          Country  treatment
4     Netherlands   0.421053
3         Ireland   0.565217
1          Canada   0.627119
2         Germany   0.636364
5  United Kingdom   0.637037